server:
  port: 6001

#\u81EA\u5B9A\u4E49\u516C\u5171\u670D\u52A1\u5668url
url: 118.190.106.207
haha: 5555

spring:
  application:
    name: member

  cloud:
    #    nacos\u914D\u7F6E
    nacos:
      #      \u670D\u52A1\u4E2D\u5FC3
      discovery:
        server-addr: ${url}:8848
  #连接池相关
  datasource:
    url: jdbc:mysql://${url}:3306/frame
    username: admin
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 100
      min-idle: 5
      min-evictable-idle-time-millis: 30000
      time-between-eviction-runs-millis: 30000
  #redis相关
  redis:
    host: ${url}
    password: 123456