#\u81EA\u5B9A\u4E49\u516C\u5171\u670D\u52A1\u5668url
url: 47.104.169.121


server:
  port: 80

spring:
  application:
    name: admin-gateway

  cloud:
    #    nacos\u914D\u7F6E
    nacos:
      #      \u670D\u52A1\u4E2D\u5FC3
      discovery:
        server-addr: ${url}:8848

    # gateway\u76F8\u5173\u914D\u7F6E
    gateway:
      discovery:
        locator:
          # \u5F00\u542F\u6309\u7167\u670D\u52A1\u540D\u79F0\u81EA\u52A8\u8F6C\u53D1\u8BF7\u6C42
          enabled: true
          # \u670D\u52A1\u540D\u79F0\u5C0F\u5199
          lower-case-service-id: true
